env:
  global:
    - CC_TEST_REPORTER_ID=d66720b9d31e440c2fbf4bac3cd92e03e757f19a1190ceac0da6ed53973dc901
language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - 'node_modules'
    
before_install:
  - npm install -g npm@2
  
script: 
  - npm run test

after_success:
- npm run coveralls