version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/db:/var/lib/postgresql/data
  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
